export const BASE_URL = ''
export const USERS_URL = '/api/v1/users'
export const FILTER_URL = '/api/v1/filter'
export const SELECT_URL = '/api/v1/movies'
export const SEARCH_URL = '/api/v1/search'
export const FAVORITE_URL = '/api/v1/favorites'